server.port: 8086
spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/online-gallery?serverTimezone=UTC
    username: online-gallery-admin
    password: online-gallery-admin